加速！加速！加速！加速！加速！加速！加速！加速！加速！加速！加速！

diff --git a/Dockerfile-podman b/Dockerfile-podman
--- a/Dockerfile-podman
+++ b/Dockerfile-podman
@@ -1,36 +1,39 @@
-#
-# Builder
-#
+FROM alpine
 
-FROM alpine AS builder
+RUN apk update && apk add --no-cache ca-certificates
 
-ARG plugins="http.cache,http.filter,http.webdav,tls.dns.cloudflare"
+RUN set -eux; \
+	mkdir -p \
+		/config/caddy \
+		/data/caddy \
+		/etc/caddy \
+		/usr/share/caddy \
+	; \
+	wget -O /etc/caddy/Caddyfile "https://raw.githubusercontent.com/caddyserver/dist/master/config/Caddyfile"; \
+	wget -O /usr/share/caddy/index.html "https://raw.githubusercontent.com/caddyserver/dist/master/welcome/index.html"
 
-RUN apk update \
-    && apk add --no-cache bash ca-certificates gzip curl \
-    && curl https://raw.githubusercontent.com/caddyserver/getcaddy.com/master/index.txt | bash -s personal ${plugins}
 
-#
-# Final stage
-#
+RUN set -eux; \
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		x86_64)  binArch='amd64' ;; \
+		armhf)   binArch='armv6' ;; \
+		armv7)   binArch='armv7' ;; \
+		aarch64) binArch='arm64' ;; \
+		ppc64el|ppc64le) binArch='ppc64le' ;; \
+		s390x)   binArch='s390x' ;; \
+		*) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+	esac; \
+	wget -O /usr/bin/caddy "https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com%2Fcaddy-dns%2Fcloudflare&p=github.com%2Fmholt%2Fcaddy-webdav"; \
+	chmod +x /usr/bin/caddy; \
+	caddy version; \
+	caddy list-modules
+	
+# set up nsswitch.conf for Go's "netgo" implementation
+# - https://github.com/docker-library/golang/blob/1eb096131592bcbc90aa3b97471811c798a93573/1.14/alpine3.12/Dockerfile#L9
+RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf
 
-FROM scratch
-LABEL maintainer "Abiola Ibrahim <abiola89@gmail.com>"
-
-# Let's Encrypt Agreement
-ENV ACME_AGREE="false"
-
-# install caddy
-COPY --from=builder /usr/local/bin/caddy /usr/bin/caddy
-COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
-
-# validate install
-#RUN /usr/bin/caddy -version
-#RUN /usr/bin/caddy -plugins
-
-EXPOSE 80 443 2015
-
-COPY Caddyfile /etc/Caddyfile
+EXPOSE 80 443 2019
 
 ENTRYPOINT ["caddy"]
-CMD ["--conf", "/etc/Caddyfile", "--log", "stdout", "--agree=true", "-quic"]
+CMD ["run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
